In [1]:
# import pandas
import pandas as pd  

# from apyori import apriori
from apyori import apriori

In [2]:
# load data 
movie_data = pd.read_csv('https://raw.githubusercontent.com/pirandello/apriori/master/movie_dataset.csv', 
                         header = None)

* explore the dataset

In [3]:
movie_data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,The Revenant,13 Hours,Allied,Zootopia,Jigsaw,Achorman,Grinch,Fast and Furious,Ghostbusters,Wolverine,Mad Max,John Wick,La La Land,The Good Dunosaur,Ninja Turtles,The Good Dunosaur Bad Moms,2 Guns,Inside Out,Valerian,Spiderman 3
1,Beirut,Martian,Get Out,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Deadpool,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,X-Men,Allied,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ninja Turtles,Moana,Ghost in the Shell,Ralph Breaks the Internet,John Wick,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
movie_data.shape

(7501, 20)

* transform dataframe to list of lists (suitable format for apyori)

In [5]:
range(len(movie_data))

range(0, 7501)

In [7]:
records = []
for i in range(len(movie_data)):
    records.append([str(movie_data.values[i, j]) for j in range(len(movie_data.columns))])

* instantiate apriori and set the input params based on following constraints:
    * we want only movies that are purchased at least 40 times
    * the minimum confidence for the rules is 20%
    * the minumum lift is 3

In [12]:
association_rules = apriori(records, min_support=40/7501, min_confidence=0.2, min_lift=3)
association_rules = list(association_rules)

* how many association rules did we obtained ?

In [13]:
len(association_rules)

32

* print the first association rule

In [14]:
association_rules[0]

RelationRecord(items=frozenset({'Green Lantern', 'Red Sparrow'}), support=0.005732568990801226, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Red Sparrow'}), items_add=frozenset({'Green Lantern'}), confidence=0.3006993006993007, lift=3.790832696715049)])

* convert association rules to DataFrame 
    * use these columns: title_1, title_2, support, confidence, lift

In [36]:
# initialize features
names_1 = []
names_2 = []
supports = []
confidences = []
lifts = []

# extract all features
for items in association_rules:
    # extract items names
    names = [item for item in items[0]]
    names_1.append(names[0])
    names_2.append(names[1])
    
    # extract support
    supports.append(items[1])
    
    # extract confidence
    confidences.append(items[2][0][2])
    
    # extract lift
    lifts.append(items[2][0][3])

In [37]:
# create dataframe
rules_dict = {'title_1': name_1, 'title_2': name_2, 'support': supports, 'confidence': confidences, 'lift':lifts}
df = pd.DataFrame(rules_dict)

In [38]:
df

          title_1                title_2   support  confidence      lift
0   Green Lantern            Red Sparrow  0.005733    0.300699  3.790833
1   Green Lantern              Star Wars  0.005866    0.372881  4.700812
2         Jumanji          Kung Fu Panda  0.015998    0.323450  3.291994
3         Jumanji           Wonder Woman  0.005333    0.377358  3.840659
4     Spiderman 3  The Spy Who Dumped Me  0.007999    0.271493  4.122410
5            Coco           The Revenant  0.005333    0.232558  3.254512
6   Green Lantern                    nan  0.005733    0.300699  3.790833
7   Green Lantern              Star Wars  0.005866    0.372881  4.700812
8         Jumanji             Tomb Rider  0.008666    0.311005  3.165328
9    The Revenant          Ninja Turtles  0.007199    0.305085  3.200616
10    Spiderman 3             Tomb Rider  0.005733    0.205742  3.124024
11   The Revenant             Tomb Rider  0.005999    0.215311  3.013149
12     Tomb Rider            World War Z  0.006666    0.239234  3.498046
13        Jumanji             Tomb Rider  0.005333    0.322581  3.283144
14        Jumanji          Ninja Turtles  0.006666    0.390625  3.975683
15        Jumanji             Tomb Rider  0.006399    0.393443  4.004360
16        Jumanji                    nan  0.015998    0.323450  3.291994
17        Jumanji             Tomb Rider  0.005999    0.523256  3.005315
18        Jumanji                    nan  0.005333    0.377358  3.840659
19    Spiderman 3                  Moana  0.007199    0.203008  3.082509
20    Spiderman 3  The Spy Who Dumped Me  0.007999    0.271493  4.130772
21           Coco           The Revenant  0.005333    0.232558  3.260596
22        Jumanji             Tomb Rider  0.008666    0.311005  3.165328
23   The Revenant          Ninja Turtles  0.007199    0.305085  3.200616
24    Spiderman 3             Tomb Rider  0.005733    0.205742  3.130361
25   The Revenant             Tomb Rider  0.005999    0.215311  3.018781
26     Tomb Rider            World War Z  0.006666    0.239234  3.498046
27        Jumanji             Tomb Rider  0.005333    0.322581  3.283144
28        Jumanji          Ninja Turtles  0.006666    0.390625  3.975683
29        Jumanji             Tomb Rider  0.006399    0.393443  4.004360
30        Jumanji             Tomb Rider  0.005999    0.523256  3.005315
31    Spiderman 3                  Moana  0.007199    0.203008  3.088761